sonar.projectKey=joanniro25_api-ci-cd
sonar.organization=joanniro25

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8